name: Deploy docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  generate_and_deploy:
    name: Generate and deploy
    runs-on: ubuntu-latest
    env:
      TESTNET_MNEMONIC: test test test test test test test test test test test junk
      POLYGON_MNEMONIC: test test test test test test test test test test test junk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm i
      - name: Generate docs
        run: npm run doc
      - name: Add Jekyll config
        run: |
          echo "theme: jekyll-theme-slate" >> docs/_config.yml
          echo "title: Sapling contracts" >> docs/_config.yml
      - name: Add index.md file
        run: |
          INDEX=$(find docs -maxdepth 2 -type f -name "*.md" -exec sh -c "echo {} | sed 's/docs\/\(.*\).\{3\}$/[\1]\(\1\)\n/'" \;)
          echo "$INDEX" > docs/index.md
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs
