name: "Check code style"

on:
  push:
    branches: [v1]
  pull_request:
    branches: [v1]

jobs:
  linter:
    name: Check storage layout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm i
      - name: Compile contracts
        run: npx hardhat compile
      - name: Check storage layout
        run: npx hardhat check | sed 's/build-info\/.*\.json/build_info\/\.\.\.\.json/g' | diff ./storageLayout/layout_1.0.2 -
