name: "Check storage layout"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linter:
    name: Check storage layout
    runs-on: ubuntu-latest
    env:
      TESTNET_MNEMONIC: test test test test test test test test test test test junk
      POLYGON_MNEMONIC: test test test test test test test test test test test junk
      ETHERSCAN_API_KEY: ""
      OPTIMISTIC_ETHERSCAN_API_KEY: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm i
      - name: Compile contracts
        run: npx hardhat compile
      - name: Check storage layout
        run: npx hardhat check | sed 's/build-info\/.*\.json/build_info\/\.\.\.\.json/g' | sed 's/)[0-9]*_storage/)_storage/g' | diff ./storageLayout/layout_1.0.1 -
