name: "Run tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TESTNET_MNEMONIC: test test test test test test test test test test test junk
      ETHERSCAN_API_KEY: ""
      OPTIMISTIC_ETHERSCAN_API_KEY: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install packages
        run: npm i
      - name: Cache Hardhat files
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/hardhat-nodejs
          key: ${{ runner.os }}-${{ hashFiles('hardhat.config.js') }}
      - name: Run tests
        run: npm test
